services:
  # The Web Service runs FastAPI and handles all incoming webhooks
  - type: web
    name: Yeab game zone 
    env: python
    region: Frankfurt # Optional: choose a region close to you
    plan: free # Or your preferred plan
    buildCommand: "apt-get update && apt-get install -y build-essential libpq-dev && pip install -r requirements.txt && alembic upgrade head"
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker api.main:app"
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Yeab game zone-db
          property: connectionString
      - key: TELEGRAM_BOT_TOKEN
        sync: false # Set in Render dashboard
      - key: CHAPA_API_KEY
        sync: false # Set in Render dashboard
      - key: WEBHOOK_URL
        fromService:
          type: web
          name: Yeab game zone 
          property: url
      - key: BOT_OWNER_ID
        sync: false # Set your Telegram User ID for admin notifications

# A PostgreSQL database managed by Render
databases:
  - name: Yeab game zone-db
    databaseName: teleludo_db
    user: teleludo_user
    plan: free # Or your preferred plan