services:
  # The Web Service runs FastAPI and handles all incoming webhooks
  - type: web
    name: Yeabkal  # Matches your service name
    env: python
    region: Frankfurt
    plan: free
    #
    # THIS IS THE COMMAND YOU ARE CHANGING:
    #
    buildCommand: "apt-get update && apt-get install -y build-essential libpq-dev && pip install -r requirements.txt"
    #
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker api.main:app"
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: yeab-game-zone-db # Make sure this is the name of your DB service on Render
          property: connectionString
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: CHAPA_API_KEY
        sync: false
      - key: WEBHOOK_URL
        fromService:
          type: web
          name: Yeabkal # Must match the service name above
          property: url
      - key: BOT_OWNER_ID
        sync: false

# A PostgreSQL database managed by Render
databases:
  - name: yeab-game-zone-db # Make sure this matches the name used above
    databaseName: yeab_game_zone_db
    user: yeab_game_zone_user
    plan: free