services:
  # The Web Service runs FastAPI and handles all incoming webhooks
  - type: web
    name: yeab-game-zone
    env: python
    region: Frankfurt # Optional: choose a region close to you
    plan: free # Or your preferred plan
    buildCommand: "apt-get update && apt-get install -y build-essential libpq-dev && pip install -r requirements.txt && alembic upgrade head"
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker api.main:app"
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: yeab-game-zone-db
          property: connectionString
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: CHAPA_API_KEY
        sync: false
      - key: WEBHOOK_URL
        fromService:
          type: web
          name: yeab-game-zone
          property: url
      - key: BOT_OWNER_ID
        sync: false

# A PostgreSQL database managed by Render
databases:
  - name: yeab-game-zone-db
    databaseName: yeab_game_zone_db
    user: yeab_game_zone_user
    plan: free # Or your preferred plan```

---

### **3. `.devcontainer/devcontainer.json`**

Updated for GitHub Codespaces.

```json
{
  "name": "Yeab Game Zone",
  "image": "mcr.microsoft.com/devcontainers/python:3.11",
  "features": {
    "ghcr.io/devcontainers/features/postgresql-nix:1": {}
  },
  "forwardPorts": [8000],
  "postCreateCommand": "pip install --user -r requirements.txt && echo 'All set! Create a .env file from .env.example and start coding.'",
  "customizations": {
    "vscode": {
      "settings": {
        "python.defaultInterpreterPath": "/usr/local/bin/python"
      },
      "extensions": [
        "ms-python.python",
        "ms-python.vscode-pylance",
        "ms-azuretools.vscode-docker"
      ]
    }
  }
}